apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260615-210219-twdrszsfj8hn-service
spec:
  selector:
    app: enterprise-system-20260615-210219-twdrszsfj8hn
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
